main: me.beezle.appletrees.AppleTrees
version: 1.1.1
name: AppleTrees
authors: [Beezle]
description: Allows for a configurable drop chance setting that makes decaying leaves drop apples and golden apples.