main: me.beezle.appletrees.AppleTrees
version: 2.0.0
name: AppleTrees
authors: [Beezle]
description: Allows for a configurable drop chance setting that makes decaying leaves drop apples and golden apples.